### ISSUE TITLE
__dirname causes errors in Electron 12

### ISSUE THREAD

**Issue by aleksey-hoffman** [nklayman/vue-cli-plugin-electron-builder#1301]
**Describe the bug**
It seems like `__dirname` variable is automatically replaced with `require("electron").remote.app.getAppPath()` in the production build, which causes errors in Electron 12, since it doesn't have the `remote` module built-in anymore.

See this issue for reference: https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/issues/1116

**To Reproduce**

- Upgrade to Electron 12
- Install remote module: https://github.com/electron/remote
- `require("electron").remote.app`

### `background.js`
```js
require('@electron/remote/main').initialize()

mainWindow = new BrowserWindow({
  ...
  webPreferences: {
    enableRemoteModule: true,
    contextIsolation: !process.env.ELECTRON_NODE_INTEGRATION,
    nodeIntegration: process.env.ELECTRON_NODE_INTEGRATION,
    nodeIntegrationInWorker: true
  }
}) 
```

**Expected behavior**

A way to specify remote module:

### `vue.config.js`
```js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      builderOptions: {
        remoteModule: require('@electron/remote')
      }
    }
  }
}
```

So that `__dirname` is replaced with `require('@electron/remote').app.getAppPath()` in production

**Comment by nklayman** [comment]
This should be fixed in a4d3f010068ac9432c3c6edf50c2f6dcdc57f57f, however I have not made a release since then. Can you try setting the version of this plugin to the git repo and let me know if that works? If it works for you I'll publish a new release.

**Comment by aleksey-hoffman** [comment]
@nklayman oh I didn't see you already addressed the issue. 

I upgraded the plugin to the latest commit, not sure if I did something wrong, but I get the following error in the production build:

```
electron/js2c/asar_bundle.js:formatted:154 
Uncaught Error: Invalid package
C:\Users\...\resources\electron.asar
    at createError (electron/js2c/asar_bundle.js:formatted:154)
    at Object.e.readFileSync (electron/js2c/asar_bundle.js:formatted:576)
    at Object.d290 (index.bundle.js:1)
    at u (index.bundle.js:1)
```

**Comment by aleksey-hoffman** [comment]
@nklayman I think there's a typo in this line:

https://github.com/nklayman/vue-cli-plugin-electron-builder/commit/a4d3f010068ac9432c3c6edf50c2f6dcdc57f57f#diff-7495814574838af7c971cccfc0210b6c62b9607ab40e1276288f722e7266ee6fR13

I think it's supposed to be a backward slash on Windows:

```js
// it should be this:
__dirname.replace("electron.asar\\renderer", "app.asar")
// Instead of this:
__dirname.replace("electron.asar/renderer", "app.asar")
```

**Comment by nklayman** [comment]
Good catch, should be fixed in the latest commit. Give that a try and let me know how it goes. Thanks!

**Comment by nklayman** [comment]
Whoops, made a typo in that commit. Fixed it now though.

**Comment by aleksey-hoffman** [comment]
@nklayman nope, still doesn't work, I think `${path.sep}` gets evaluated to a single backward `\` slash. The error still specifies the `C:\Users\...\resources\electron.asar` path, which means it's not replacing the string. 

I tried hardcoding double backward `\\` slashed but it throws the same error as the `${path.sep}`:
```
? '__dirname.replace("electron.asar\\renderer", "app.asar")'
```

I managed to make it work by specifying the hardcoded path to the `app.asar` file **with forward slashes** weirdly enough :

```
? '"C:/APP_PATH/resources/app.asar"'
```

- But how do we make it dynamic?

- Also when I run `__dirname` in the console (production build), it shows `...resources\electron.asar\renderer` which means modules, like the one I specified in the post, would still cause the error when they use `__dirname`, right?

**Comment by aleksey-hoffman** [comment]
@nklayman nope, the same error, I think `${path.sep}` gets evaluated to a single backward `\` slash. The error still specifies the `C:\APP_PATH\resources\electron.asar` path, which means it's not replacing the string. 

I tried hardcoding double backward `\\` slashes but it results in the same error as with the `${path.sep}`:
```
? '__dirname.replace("electron.asar\\renderer", "app.asar")'
```

I managed to make it work by specifying the hardcoded path to the `app.asar` file **with forward slashes** weirdly enough :

```
? '"C:/APP_PATH/resources/app.asar"'
```

- But how do we make it dynamic? I think there's a problem with the function that replaces the expression string

- Also when I run `__dirname` in the console (production build), it returns `C:\APP_PATH\resources\electron.asar\renderer` which means modules, like the one I specified in the post, would still cause the error when they use `__dirname`, right? Or not? is the path supposed to end with `\renderer`?

**Comment by aleksey-hoffman** [comment]
@nklayman nope, the same error but I found the solution, 

I think `${path.sep}` gets evaluated to a single backward `\` slash. The error still specifies the `C:\APP_PATH\resources\electron.asar` path, which means it's not replacing the string. I also tried hardcoding double backward `\\` slashes but it results in the same error.

I managed to make it work with the following expression:

```
? '__dirname.replace(/\\\\/g, "/").replace("electron.asar/renderer", "app.asar")'
```

So replace the current line with this one and it's all good.

Now, another problem with this is, when I run `__dirname` in the console (production build), it returns `C:\APP_PATH\resources\electron.asar\renderer` which means modules, like the one I specified in the post, would still cause the error when they use `__dirname`, right?

**Comment by nklayman** [comment]
Just pushed another commit that should fix it for real. Try that and let me know if it works. Thanks for your help debugging!

**Comment by aleksey-hoffman** [comment]
@nklayman thanks. I just checked this commit, it works on Windows. But will it also work on Linux / Mac? I suppose the expression that you used in the commit does exactly the same thing as the one I specified in the previous comment, right?

**Comment by nklayman** [comment]
Sweet, glad that it works. Since I'm using `path.sep`, it will work on linux and mac too. However, it wouldn't work if you cross-compiled actually, so I'll have to update it to work there.

**Comment by nklayman** [comment]
Okay, just pushed a commit that adds cross-compiling support. It works for me on linux, can you make sure it works for you on windows? Thanks!

**Comment by nklayman** [comment]
You don't need to cross-compile or anything, just build and run the exe.

**Comment by aleksey-hoffman** [comment]
@nklayman yep the last commit also works on Windows.

```js
console.log(__dirname)
// C:\APP_PATH\resources\app.asar

console.log(require('@electron/remote').app.getAppPath())
// C:\APP_PATH\resources\app.asar
```
